modLoader="javafml"
loaderVersion="[4,)"
license="Custom"

[[mods]]
modId="cbcmoreshells"
version="2.0.2-1.21.1"
displayName="CBC Military Supplement"
displayURL="https://www.curseforge.com/minecraft/mc-mods/"
logoFile=""
credits=""
authors="cainiao1053"
description='''
Supplements...
'''

[[mixins]]
config = "cbcmoreshells.mixins.json"

[[dependencies.cbcmoreshells]] #optional
modId = "neoforge"
type = "required"
versionRange="21.1.225"
ordering="AFTER"
side="SERVER"

[[dependencies.cbcmoreshells]]
modId="minecraft"
type = "required"
versionRange="[1.21,1.22)"
ordering="AFTER"
side="SERVER"

[[dependencies.cbcmoreshells]]
modId="create"
type = "required"
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cbcmoreshells]]
modId="createbigcannons"
type = "required"
versionRange="[5.11.0,)"
ordering="AFTER"
side="BOTH"

